apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-juan-deployment
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-juan
  template:
    metadata:
      labels:
        app: producer-juan
    spec:
      containers:
        - name: producer-juan-container
          image: juanloaiza007/producer-juan:latest
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: producer-juan-service
spec:
  selector:
    app: producer-juan
  ports:
    - protocol: TCP
      port: 8000 # Puerto interno dentro del clúster
      targetPort: 8000 # Puerto del contenedor
  type: ClusterIP
