apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-juan-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-juan
  template:
    metadata:
      labels:
        app: producer-juan
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: producer
                    operator: In
                    values:
                      - juan
      containers:
        - name: producer-juan-container
          image: juanloaiza007/producer-juan:latest
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: kafka_address
            - name: TOPIC_NAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: topic_name

---
apiVersion: v1
kind: Service
metadata:
  name: producer-juan-service
spec:
  selector:
    app: producer-juan
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
